apiVersion: v1
kind: Namespace
metadata:
  name: pubsub-consumer-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pubsub-consumer-demo-sa
  namespace: pubsub-consumer-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: pubsub-consumer-demo-sa@rocketech-de-pgcp-sandbox.iam.gserviceaccount.com
  name: pubsub-consumer-demo-sa
  namespace: pubsub-consumer-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autopilot-pubsub-consumer
  namespace: pubsub-consumer-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autopilot-pubsub-consumer
  template:
    metadata:
      labels:
        app: autopilot-pubsub-consumer
    spec:
      serviceAccountName: pubsub-consumer-demo-sa # this is to tell which KSA to use for this service
      containers:
        - name: subscriber
          image: europe-west2-docker.pkg.dev/rocketech-de-pgcp-sandbox/demo/autopilot-pubsub-consumer:v1.0.0
          env:
            - name: PROJECT_ID
              value: "rocketech-de-pgcp-sandbox"
            - name: SUBSCRIPTION_ID
              value: "autopilot-test-sub"
          resources:
            requests:
              cpu: 200m
              memory: 250Mi